[workspace]
members = [
    "basm",
    "basm-std",
    "basm-macro"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
overflow-checks = false
codegen-units = 1
strip = true
